language: cpp
compiler:
  - gcc
  - clang
cache: apt
notifications:
  recipients:
    david.weese@fu-berlin.de
  email:
    on_success: change
    on_failure: always
before_script:
  sudo apt-get install -qq cmake python zlib1g-dev libbz2-dev libboost-dev
script:
  ./util/travis/linux-cibuild.sh
